# Generated by Django 6.0.5 on 2026-05-19 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'aéroport")),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la compagnie')),
                ('description', models.TextField(blank=True, null=True)),
                ('pays_rattachement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, verbose_name='Constructeur')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle exact')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('longueur_piste_necessaire', models.IntegerField(help_text="Distance d'atterrissage minimale en mètres")),
            ],
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de piste')),
                ('longueur', models.IntegerField(help_text='Longueur en mètres')),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistes', to='gestion_trafic.aeroport')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Immatriculation')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flotte', to='gestion_trafic.compagnie')),
                ('type_avion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appareils', to='gestion_trafic.typeavion')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilote', models.CharField(max_length=150, verbose_name='Nom du pilote')),
                ('date_heure_depart', models.DateTimeField(verbose_name='Date/Heure de départ')),
                ('date_heure_arrivee', models.DateTimeField(verbose_name="Date/Heure d'arrivée")),
                ('aeroport_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_arrivee', to='gestion_trafic.aeroport')),
                ('aeroport_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_depart', to='gestion_trafic.aeroport')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols', to='gestion_trafic.avion')),
            ],
        ),
    ]
