# Generated by Django 6.0.5 on 2026-05-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_trafic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeavion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_avions/', verbose_name="Photo de l'appareil"),
        ),
    ]
